// UK lang variables

tinyMCE.addToLang('media',{
title : 'Вставить / редактировать встроенное медиа',
desc : 'Вставить / редактировать встроенное медиа',
general : 'Основные',
advanced : 'Расширенные',
file : 'Файл/URL',
list : 'Список',
size : 'Размеры',
preview : 'Предпросмотр',
constrain_proportions : 'Сохранять пропорции',
type : 'Тип',
id : 'Id',
name : 'Имя',
class_name : 'Класс',
vspace : 'Высота',
hspace : 'Ширина',
play : 'Автовоспроизведение',
loop : 'Повторять',
menu : 'Показывать меню',
quality : 'Качество',
scale : 'Масштаб',
align : 'Выравнивание',
salign : 'SAlign',
wmode : 'WMode',
bgcolor : 'Фон',
base : 'Base',
flashvars : 'Flashvars',
liveconnect : 'SWLiveConnect',
autohref : 'AutoHREF',
cache : 'Кэш',
hidden : 'Прятать',
controller : 'Контроллер',
kioskmode : 'Режим киоска',
playeveryframe : 'Играть каждый кадр',
targetcache : 'Целевой кэш',
correction : 'Без коррекции',
enablejavascript : 'Разрешить JavaScript',
starttime : 'Время начала',
endtime : 'Время конца',
href : 'Href',
qtsrcchokespeed : 'Скорость choke',
target : 'Цель',
volume : 'Громкость',
autostart : 'Автовоспроизведение',
enabled : 'Включено',
fullscreen : 'Полный экран',
invokeurls : 'Вызвать URLs',
mute : 'Выкл.звук',
stretchtofit : 'Подстроить размер',
windowlessvideo : 'Видео без окна',
balance : 'Баланс',
baseurl : 'Основной URL',
captioningid : 'id заголовка',
currentmarker : 'Текущий маркер',
currentposition : 'Текущая позиция',
defaultframe : 'Кадр по-умолчанию',
playcount : 'Счетчик проигрывания',
rate : 'Рейтинг',
uimode : 'UI режим',
flash_options : 'Настройки Flash',
qt_options : 'Настройки Quicktime',
wmp_options : 'Настройки Windows медиа проигрывателя',
rmp_options : 'Настройки Real медиа проигрывателя',
shockwave_options : 'Настройки Shockwave',
autogotourl : 'URL автоматического перехода',
center : 'Центр',
imagestatus : 'Статус картинки',
maintainaspect : 'Maintain aspect',
nojava : 'Без java',
prefetch : 'Предварительно подгружать',
shuffle : 'Случайный порядок',
console : 'Консоль',
numloop : 'Num loops',
controls : 'Управления',
scriptcallbacks : 'Вызываемые скрипты',
swstretchstyle : 'Подстроить стиль',
swstretchhalign : 'Подстроить выравнивание по ширине',
swstretchvalign : 'Подстроить выравнивание по высоте',
sound : 'Звук',
progress : 'Прогресс',
qtsrc : 'QT источник',
qt_stream_warn : 'Потоковые ресурсы rtsp должны быть добавлены в поле QT Src на закладке Расширенные.\nВы также должны добавить не потоковую версию в поле Источник..',
align_top : 'Сверху',
align_right : 'Справа',
align_bottom : 'Снизу',
align_left : 'Слева',
align_center : 'По центру',
align_top_left : 'Сверху слева',
align_top_right : 'Сверху справа',
align_bottom_left : 'Снизу слева',
align_bottom_right : 'Снизу справа'
});