// UK lang variables

tinyMCE.addToLang('style',{
title : 'Редактировать стиль CSS',
styleinfo_desc : 'Редактировать стиль CSS',
apply : 'Применить',
text_tab : 'Текст',
background_tab : 'Фон',
block_tab : 'Блок',
box_tab : 'Бокс',
border_tab : 'Граница',
list_tab : 'Список',
positioning_tab : 'Позиция',
text_props : 'Текст',
text_font : 'Шрифт',
text_size : 'Размер',
text_weight : 'Вес',
text_style : 'Стиль',
text_variant : 'Вариант',
text_lineheight : 'Высота линии',
text_case : 'Регистр',
text_color : 'Цвет',
text_decoration : 'Декорация',
text_overline : 'сверху',
text_underline : 'снизу',
text_striketrough : 'зачеркнутый',
text_blink : 'мигающий',
text_none : 'нет',
background_color : 'Цвет фона',
background_image : 'Изображение фона',
background_repeat : 'Повторять',
background_attachment : 'Аттачмент',
background_hpos : 'Горизонтальная позиция',
background_vpos : 'Вертикальная позиция',
block_wordspacing : 'Расстояние между словами',
block_letterspacing : 'Расстояние между символами',
block_vertical_alignment : 'Выравнивание по вертикали',
block_text_align : 'Выравнивание текста',
block_text_indent : 'Единица размера текста',
block_whitespace : 'Whitespace',
block_display : 'Показывать',
box_width : 'Ширина',
box_height : 'Высота',
box_float : 'Плавающий',
box_clear : 'Чистый',
padding : 'Padding',
same : 'Одинаково для всех',
top : 'Сверху',
right : 'Справа',
bottom : 'Снизу',
left : 'Слева',
margin : 'Margin',
style : 'Силь',
width : 'Ширина',
height : 'Высота',
color : 'Цвет',
list_type : 'Тип',
bullet_image : 'Изображение точки',
position : 'Позиция',
positioning_type : 'Тип',
visibility : 'Видимость',
zindex : 'Z-индекс',
overflow : 'Переполнение',
placement : 'Размещение',
clip : 'Вырезать'
});
