// UK lang variables

tinyMCE.addToLang('xhtmlxtras',{
cite_desc : 'Цитата',
abbr_desc : 'Аббревиатура',
acronym_desc : 'Акроним',
del_desc : 'Удаление',
ins_desc : 'Вставка',
attribute_label_title : 'Заголовок',
attribute_label_id : 'ID',
attribute_label_class : 'Класс',
attribute_label_style : 'Стиль',
attribute_label_cite : 'Cite',
attribute_label_datetime : 'Дата/Время',
attribute_label_langdir : 'Направление текста',
attribute_option_ltr : 'Слева направо',
attribute_option_rtl : 'Справа налево',
attribute_label_langcode : 'Язык',
attribute_label_tabindex : 'TabIndex',
attribute_label_accesskey : 'AccessKey',
attribute_label_cite : 'Cite',
attribute_events_tab : 'События',
attribute_attrib_tab : 'Аттрибуты',
general_tab : 'Основные',
attrib_tab : 'Аттрибуты',
events_tab : 'События',
fieldset_general_tab : 'Основные настройки',
fieldset_attrib_tab : 'Аттрибуты элементов',
fieldset_events_tab : 'События элементов',
title_ins_element : 'Вставка элемента',
title_del_element : 'Удаление элемента',
title_acronym_element : 'Акроним элемента',
title_abbr_element : 'Аббревиатура элемента',
title_cite_element : 'Цитирование элемента',
remove : 'Удалить',
not_set : '-не задано-',
insert_date : 'Вставить текущую дату/время',
option_ltr : 'Слева направо',
option_rtl : 'Справа налево',
attribs_desc : 'Вставить/изменить аттрибуты',
attribs_title : 'Вставить/изменить аттрибуты'
});
