// UK lang variables

tinyMCE.addToLang('advlink',{
general_tab : 'Основные',
popup_tab : 'Всплывающие окна',
events_tab : 'События',
advanced_tab : 'Расширенные',
general_props : 'Основные свойства',
popup_props : 'Свойства всплывающих окон',
event_props : 'События',
advanced_props : 'Расширенные свойства',
popup_opts : 'Настройки',
anchor_names : 'Якоря',
target_same : 'Открывать в этом окне / фрейме',
target_parent : 'Открывать в родительском окне / фрейме',
target_top : 'Открывать в главном фрейме (заменяет все фреймы)',
target_blank : 'Открывать в новом окне',
popup : 'Всплывающий Javascript',
popup_url : 'URL всплывающего окна',
popup_name : 'Имя окна',
popup_return : 'Вставить \'return false\'',
popup_scrollbars : 'Показать полосы прокрутки',
popup_statusbar : 'Показать панель статуса',
popup_toolbar : 'Показать панели кнопок',
popup_menubar : 'Показать панель меню',
popup_location : 'Показать панель адреса',
popup_resizable : 'Разрешить изменение размеров окна',
popup_dependent : 'Зависимость (только Mozilla/Firefox)',
popup_size : 'Размер',
popup_position : 'Позиция (X/Y)',
id : 'Id',
style: 'Стиль',
classes : 'Классы',
target_name : 'Имя цели',
langdir : 'Направление языка',
target_langcode : 'Язык цели',
langcode : 'Код языка',
encoding : 'Кодировка цели',
mime : 'Тип MIME цели',
rel : 'Связь страницы к цели',
rev : 'Связь цели к странице',
tabindex : 'Tabindex',
accesskey : 'Accesskey',
ltr : 'Слева направо',
rtl : 'Справа налево'
});